Script to expand environment variables in a file
This is an alternative to envsubst (or similar) utilities which is
dependency free, which means i can run it as part of my setup.

Note that it is not pin-compatible with envsubst or shell expansion, the
expression form is more limited, there is no provision for escaping, and
most importantly non-existent variables are left in variable form.

diff --git a/test/common b/test/common
--- a/test/common
+++ b/test/common
@@ -53,14 +53,32 @@ cleanup() {
 trap 'cleanup ; trap - ERR EXIT' ERR EXIT
 trap 'cleanup ; trap - INT ; kill -INT $$' INT
 
-run_test_unchecked() {
+invoke_command_unchecked() {
   local test_name="${1:?}"
   shift
   # Clean up previous tests, so that accidental use of the wrong output is caught earlier
   rm -f "${output_dir}"/*.{out,err}(N)
   local stdout="${output_dir}/${test_name}.out"
   local stderr="${output_dir}/${test_name}.err"
-  "${script_under_test}" "$@" 1>"${stdout}" 2>"${stderr}"
+  "$@" 1>"${stdout}" 2>"${stderr}"
+  return "$?"
+  # Caller checks exit code, if they forget, set -e above will keep them honest
+}
+
+invoke_command_checked() {
+  local test_name="${1:?}"
+  local test_location="${2:?}"
+  shift 2
+  invoke_command_unchecked "${test_name}" "$@" || {
+    exit_code="$?"
+    failed "${test_name}" "${test_location}" "Exit code ${exit_code} from ${script_under_test}"
+  }
+}
+
+run_test_unchecked() {
+  local test_name="${1:?}"
+  shift
+  invoke_command_unchecked "${test_name}" "${script_under_test}" "$@"
   return "$?"
   # Caller checks exit code, if they forget, set -e above will keep them honest
 }
@@ -69,10 +87,15 @@ run_test() {
   local test_name="${1:?}"
   local test_location="${2:?}"
   shift 2
-  run_test_unchecked "${test_name}" "$@" || {
-    exit_code="$?"
-    failed "${test_name}" "${test_location}" "Exit code ${exit_code} from ${script_under_test}"
-  }
+  invoke_command_checked "${test_name}" "${test_location}" "${script_under_test}" "$@"
+}
+
+run_test_wrapped() {
+  local test_name="${1:?}"
+  local test_location="${2:?}"
+  local wrapper="${3:?}"
+  shift 3
+  invoke_command_checked "${test_name}" "${test_location}" "${wrapper}" "${script_under_test}" "$@"
 }
 
 verify_stdout() {
