Bug fixes and style improvements for daily scripts
- Move snapshot to a subdirectory of backup
  - the new directory was running afoul of TCC checks.
  - I'm not sure how i originally set up backup to avoid this, for now
    it's easiest to sidestep the issue
- Prefer -efx on #! to set in body
- Format based logging with datestamps
- Don't do potentially failing operations in interpolations, as error
  codes are suppressed.

diff --git a/libexec/daily-backup b/libexec/daily-backup
--- a/libexec/daily-backup
+++ b/libexec/daily-backup
@@ -1,12 +1,12 @@
-#!/bin/zsh
-
-set -e
+#!/bin/zsh -e
 
 log() {
-  printf '%s: %s\n' "$(date)" "$*"
+  local fmt="${1:?}"
+  shift
+  print -f "%s: ${fmt}\n" -- "$(date)" "$@"
 }
 
-error() {
+fail() {
   log "$@"
   exit 1
 }
@@ -14,11 +14,12 @@ error() {
 BACKUP_ROOT=~/cloud/backup
 if [[ ! -d "${BACKUP_ROOT}" ]]
 then
-  error "No backup root at '${BACKUP_ROOT}', cannot backup"
+  fail 'No backup root at %s, cannot backup' "${(q+)BACKUP_ROOT}"
 else
   BACKUP_DIR="${BACKUP_ROOT}/$(date +'%Y-%m-%d')"
-  log "Backing up to '${BACKUP_DIR}'"
-  mkdir "${BACKUP_DIR}" || error "Partial backup at '${BACKUP_DIR}', giving up"
+  log 'Backing up to %s' "${(q+)BACKUP_DIR}"
+
+  mkdir "${BACKUP_DIR}" || fail 'Partial backup at %s, giving up' "${(q+)BACKUP_DIR}"
 
   sqlite3 "${HALFYAK_ETC_SQLITE_HISTORY_DB}" '.dump' \
     | bzip2 --stdout \
@@ -27,5 +28,7 @@ else
 
   cp "${HOME}/.docker/config.json" "${BACKUP_DIR}/docker-config.json"
 
-  log "$(du -sh "${BACKUP_DIR}")"
+  local size
+  size="$(du -sh "${BACKUP_DIR}")"
+  log 'Backup Size: %s' "${size}"
 fi
diff --git a/libexec/daily-snapshot b/libexec/daily-snapshot
--- a/libexec/daily-snapshot
+++ b/libexec/daily-snapshot
@@ -1,9 +1,9 @@
-#!/bin/zsh -ef
+#!/bin/zsh -e
 
 log() {
   local fmt="${1:?}"
   shift
-  print -f "$fmt\n" -- "$@"
+  print -f "%s: ${fmt}\n" -- "$(date)" "$@"
 }
 
 fail() {
@@ -11,30 +11,38 @@ fail() {
   exit 1
 }
 
-SERIAL="$(system_profiler -json SPHardwareDataType | jq --raw-output '.SPHardwareDataType[0].serial_number')"
-SNAPSHOT_ROOT="${HOME}/Documents/etc/local/${SERIAL}"
-
-if [[ ! -d "${SNAPSHOT_ROOT}" ]]
+BACKUP_ROOT=~/cloud/backup
+if [[ ! -d "${BACKUP_ROOT}" ]]
 then
-  fail 'No snapshot root at %s, cannot snapshot' "${(q+)SNAPSHOT_ROOT}"
+  fail 'No backup root at %s, cannot snapshot' "${(q+)BACKUP_ROOT}"
 else
+  SNAPSHOT_DIR="${BACKUP_ROOT}/snapshot"
+  log 'Snapshotting to %s' "${(q+)SNAPSHOT_DIR}"
+
+  mkdir -p "${SNAPSHOT_DIR}" || fail 'Cannot create %s, giving up' "${(q+)SNAPSHOT_DIR}"
+
   for dir in ~/src/*(/)
   do
     local name="${dir##*/}"
-    local snapshot="${SNAPSHOT_ROOT}/src/${name}"
+    local snapshot="${SNAPSHOT_DIR}/src/${name}"
     mkdir -p "${snapshot}"
     git -C "${dir}" config get remote.origin.url > "${snapshot}/remote.origin.url"
   done
 
-  asdf list > "${SNAPSHOT_ROOT}/asdf"
+  asdf list > "${SNAPSHOT_DIR}/asdf"
 
-  mkdir -p "${SNAPSHOT_ROOT}/alfredapp"
+  mkdir -p "${SNAPSHOT_DIR}/alfredapp"
   rsync --checksum --delete --links --recursive \
     ~/"Library/Application Support/Alfred/Alfred.alfredpreferences"/ \
-    "${SNAPSHOT_ROOT}/alfredapp/Alfred.alfredpreferences"/
+    "${SNAPSHOT_DIR}/alfredapp/Alfred.alfredpreferences"/
 
-  mkdir -p "${SNAPSHOT_ROOT}/iterm"
+  mkdir -p "${SNAPSHOT_DIR}/iterm"
   rsync --checksum --delete --links --recursive \
     ~/"Library/Preferences/com.googlecode.iterm2.plist" \
-    "${SNAPSHOT_ROOT}/iterm/com.googlecode.iterm2.plist"
+    "${SNAPSHOT_DIR}/iterm/com.googlecode.iterm2.plist"
+
+
+  local size
+  size="$(du -sh "${SNAPSHOT_DIR}")"
+  log 'Snapshot Size: %s' "${size}"
 fi
