Add Safari Develop menu to audit
Also, upgrade the check infra here to use a helper for both safari and
universalaccess defaults json access. I've not yet included the pbs
global key equivalents in this.

diff --git a/libexec/Darwin/audit-system-settings b/libexec/Darwin/audit-system-settings
--- a/libexec/Darwin/audit-system-settings
+++ b/libexec/Darwin/audit-system-settings
@@ -11,7 +11,7 @@ fail() {
   exit 1
 }
 
-errors=0
+ERRORS=0
 
 checkKeyEquivalent() {
   local pbsJson="${1:?}"
@@ -28,7 +28,7 @@ checkKeyEquivalent() {
       log ":; open 'x-apple.systempreferences:com.apple.Keyboard-Settings.extension?Shortcuts'"
       log 'In Services tab, under Text in right hand pane, set shortcut for "%s" to %s' "${name}" "${setting}"
       log ' '
-      ((errors += 1))
+      ((ERRORS += 1))
   }
 }
 
@@ -45,23 +45,64 @@ checkKeyEquivalent() {
     'Search man Page Index in Terminal' 'none'
 } =(true)
 
-() {
-  local safariJson="${1:?}"
-  defaults-json com.apple.Safari > "${safariJson}"
-  local check
-  # This hack makes Cmd+W still Close Tab even for the last unpinned tab, which avoids closing the window (and
-  # the pinned tabs) when i close the last unpinned tab.
-  check="$(jq '.["com.apple.Safari"].NSUserKeyEquivalents.["Close Tab"] // empty' < "${safariJson}")"
-  [[ "${check}" == '"@w"' ]] || {
-      log 'Shortcut for Safari Close Tab set to %s not Cmd+W' "${(q+)check:-default}"
-      log ":; open 'x-apple.systempreferences:com.apple.Keyboard-Settings.extension?Shortcuts'"
-      log 'In App Shortcuts tab, use + to add application Safari.app, Menu title "Close Tab", Keyboard shortcut Cmd+W'
-      log ' '
-      ((errors += 1))
-  }
-} =(true)
+validateDefaultsWithJq() {
+  local domain="${1:?}"
+  local jqScript="${2:?}"
+  local heading="${3:?}"
+  shift 3
+  () {
+    local defaultsJson="${1:?}"
+    shift 1
+    defaults-json "${domain}" > "${defaultsJson}"
+    local domainErrors
+    domainErrors=(${(f)"$(jq --raw-output --from-file "${jqScript}" < "${defaultsJson}")"})
+    [[ "${#domainErrors}" -eq 0 ]] || {
+        local line
+        log '%s' "${heading}"
+        for line in "${(@)domainErrors}"
+        do
+          log '%s' "${line}"
+        done
+        for epilog in "$@"
+        do
+          log '%s' "${epilog}"
+        done
+        log ' '
+        ((ERRORS += 1))
+    }
+  } =(true) "$@"
+}
 
-JQ_CHECK_CURSOR_SETTINGS="$(<<'END_JQ'
+JQ_SAFARI="$(<<'END_JQ'
+.["com.apple.Safari"]
+| . as { $IncludeDevelopMenu, $NSUserKeyEquivalents }
+| [ if $IncludeDevelopMenu
+    then empty
+    else
+      [ "Safari Develop Menu not enabled"
+      , "Safari Settings, Advanced Tab, check 'Show features for web developers'"
+      ]
+    end
+  , ( ( $NSUserKeyEquivalents.["Close Tab"] // "default" ) as $closeTab
+    # This hack makes Cmd+W still Close Tab even for the last unpinned tab, which avoids closing the window (and
+    # the pinned tabs) when i close the last unpinned tab.
+    | if $closeTab == "@w"
+      then empty
+      else
+        [ "Shortcut for Safari Close Tab set to \($closeTab) not Cmd+W"
+        , ":; open 'x-apple.systempreferences:com.apple.Keyboard-Settings.extension?Shortcuts'"
+        , "In App Shortcuts tab, use + to add application Safari.app, Menu title 'Close Tab', Keyboard shortcut Cmd+W"
+        ]
+      end
+    )
+  ]
+| map("\(.[])\n") | join("")
+END_JQ
+)"
+
+validateDefaultsWithJq com.apple.Safari <(<<<"${JQ_SAFARI}") "Safari configuration errors:"
+
+JQ_UNIVERSAL_ACCESS="$(<<'END_JQ'
 .["com.apple.universalaccess"]
 | . as { $cursorOutline, $cursorFill, $mouseDriverCursorSize }
 | [ if $mouseDriverCursorSize == 2.5
@@ -81,22 +122,8 @@ JQ_CHECK_CURSOR_SETTINGS="$(<<'END_JQ'
 END_JQ
 )"
 
-() {
-  local universalAccessJson="${1:?}"
-  defaults-json com.apple.universalaccess > "${universalAccessJson}"
-  local cursorErrors
-  cursorErrors=(${(f)"$(jq --raw-output --from-file <(<<<"${JQ_CHECK_CURSOR_SETTINGS}") < "${universalAccessJson}")"})
-  [[ "${#cursorErrors}" -eq 0 ]] || {
+validateDefaultsWithJq com.apple.universalaccess <(<<<"${JQ_UNIVERSAL_ACCESS}") \
+  "Pointer settings (mouse cursor) are not correct:" \
+  ":; open 'x-apple.systempreferences:com.apple.preference.universalaccess?pointer'"
 
-      local line
-      log "Pointer settings (mouse cursor) are not correct:"
-      for line in "${(@)cursorErrors}"
-      do
-        log '%s' "${line}"
-      done
-      log ":; open 'x-apple.systempreferences:com.apple.preference.universalaccess?pointer'"
-      ((errors += ${#cursorErrors}))
-  }
-} =(true)
-
-[[ "${errors}" -eq 0 ]] || fail "Audit failed (${errors} errors) - see above"
+[[ "${ERRORS}" -eq 0 ]] || fail "Audit failed (${ERRORS} errors) - see above"
